# .golangci.pipeline.yaml  (для golangci-lint v1.x)

linters:
  disable-all: true
  enable:
    - errcheck
    - goconst
    - goimports
    - gosec
    - govet
    - ineffassign
    - revive
    - typecheck
    - unused

linters-settings:
  govet:
    enable:
      - shadow
    settings:
      shadow:
        strict: false   # поставьте true, если хотите более строгие срабатывания
  dupl:
    threshold: 100
  goconst:
    min-len: 2
    min-occurrences: 2

run:
  concurrency: 8
  timeout: 10m
  issues-exit-code: 1
  tests: true
  # при желании зафиксируйте целевую версию Go для анализаторов:
  # go: '1.23'

output:
  formats:
    - format: colored-line-number
      path: stdout
  print-issued-lines: true
  print-linter-name: true

issues:
  exclude-use-default: false
  exclude:
    - G104                                   # подавить конкретный ID из gosec
    - exported func .* returns unexported type .*, which can be annoying to use
    - should have a package comment
    - don't use an underscore in package name
  exclude-files:
    - \.pb\.go$
    - \.pb\.gw\.go$
  exclude-dirs:
    - bin
    - vendor
    - var
    - tmp
    - \.cache