syntax = "proto3";

package noteV1;

import "google/protobuf/empty.proto";
import "google/protobuf/timestamp.proto";
import "google/protobuf/wrappers.proto";

option go_package = "github.com/olezhek28/microservices_course_boilerplate/gen/auth/v1/;v1";

service UserAPI {
  rpc Create (CreateRequest) returns (CreateResponse);
  rpc Get (GetRequest) returns (GetResponse);
  rpc Update (UpdateRequest) returns (google.protobuf.Empty);
  rpc Delete (DeleteRequest) returns (google.protobuf.Empty);
}

message UserInfo {
 string name = 1;
 string email = 2;
 enum role {
   ROLE_UNSPECIFIED = 0;
   ROLE_USER = 1;
   ROLE_ADMIN = 2;
 }
}

message GetUser {
  int64 id = 1;
  UserInfo user = 2;
  google.protobuf.Timestamp created_at = 3;
  google.protobuf.Timestamp updated_at = 4;
}

message UserPassword {
  UserInfo user = 1;
  string password = 2;
  string password_confirm = 3;
}

message UserUpdate {
  int64 id = 1;
 google.protobuf.StringValue name = 2;
 google.protobuf.StringValue email = 3;
}

message CreateRequest {
  UserPassword user = 1;
}

message CreateResponse {
  int64 id = 1;
}

message GetRequest {
  int64 id = 1;
}

message GetResponse {
  GetUser user = 1;
}

message UpdateRequest {
  UserUpdate  user = 1;
}

message DeleteRequest {
  int64 id = 1;
}